### ISSUE TITLE
T440 whitelist

### ISSUE THREAD

**Issue by goldwoods2005** [digmorepaka/thinkpad-firmware-patches#14]
I do patch my bios with the patch file provided, but after flash back to the bios chip ; It is not working.
My Bios version: 2.52 (the latest one)
I see that, The tested just on the bios 2.41.

My Dump Bios from flashrom :https://drive.google.com/file/d/1VfIPq9IYaQaMMazW0DTnYnkv889cCGB8/view?usp=sharing

Many Thanks

**Comment by digmorepaka** [comment]
Rom looks fine. did you replace `4E 56 42 42 53 45 43 FB` with `4E 56 42 42 53 45 43 FF` on your patched rom?

**Comment by goldwoods2005** [comment]
> Rom looks fine. did you replace `4E 56 42 42 53 45 43 FB` with `4E 56 42 42 53 45 43 FF` on your patched rom?

I did sign the patch rom with thrimbor/thinkpad-uefi-sign before flash bios.

My Patch Bios https://drive.google.com/file/d/1PqN4lJg87CbwiUOEBxVjElFQI3HoF1Zc/view?usp=sharing

**Comment by digmorepaka** [comment]
That currently doesn't work on the  T440.

**Comment by goldwoods2005** [comment]
I tried to downgrade bios but it can't be done.
I forgeted to mention you my devices is T440. 

So happy that you replied so quickly
Thanks

**Comment by goldwoods2005** [comment]
It's me again.
So I did not patch with the code replace 4E 56 42 42 53 45 43 FB with 4E 56 42 42 53 45 43 FF, I tried the luck again, and boom. It's worked. (Try to replace with 3165 card, no problems, stable signal)

I can confirm the patch work on latest bios (2.54) Please update the text.
Many thanks.

**Comment by p4block** [comment]
@digmorepaka This also happened to me, I didn't get that "TPM: No" meant that I shouldn't be using sign.py 
I was pretty asleep when I was doing this, but maybe the README lacks a notice about it. Right now it tells you that sign.py is for "xx40 ThinkPads" of which this one is a part of! 

In any case, only one bios chip vs my x230 made this a breeze and I was able to get it on the second try. 
Awesome work on this, thanks a million

**Comment by katschub88** [comment]
I've got a T440 (Intel i5 4300U, BIOS version 2.54) and the RAM is not soldered, it has 1 SO-DIMM slot.
I have a "Security Chip" option in BIOS, which allows me to switch between "Discrete TMP" (TPM 1.2 mode) and "Intel PTT" (TPM 2.0 mode).
My original BIOS dump is 16GB and verify.py shows "SIGNATURES CORRECT!", which means that it is signed.

When I applied the patches and used sign.py (and verify.py) on the patched version, the notebook did not start anymore (F1, F4, Fn keys lit up for less than a second, then the notebook turned off).

Since my BIOS chip cannot be read or written with a test clip, I have to unsolder it every time to programm it. So I'd like to make sure that I get it right this time:
Do I need to apply this HEX patch only and leave the BIOS unsigned (even though the original is signed) or do I have to change that HEX value and also sign the BIOS file? The README states that the "4E 56 42 42 53 45 43 FB to 4E 56 42 42 53 45 43 FF" changes only apply to soldered ram, but using sign.py alone leads to a non-working notebook.
Can anyone confirm the correct steps?

**Comment by digmorepaka** [comment]
> the "4E 56 42 42 53 45 43 FB to 4E 56 42 42 53 45 43 FF" 


Yeah use that for T440

**Comment by katschub88** [comment]
> Yeah use that for T440

When I disable bootguard with the HEX method and don't sign the BIOS, the system starts, but the TPM is disabled (MFG mode).
Not sure what else is not working with that method.
The original BIOS is signed, verify.py shows a valid signature.
When I use thrimbor's sign.py, the modded BIOS, the system does not start.
(Even if I take the original BIOS and simply sign it again, the notebook won't start)
So it seems that its signing method is not compatible with the T440.
Is there another signing tool or method that might work here?

**Comment by digmorepaka** [comment]
>When I disable bootguard with the HEX method and don't sign the BIOS

it's phoenix's biosguard, different region

>TPM is disabled (MFG mode).

yes, that's what happens when you turn off biosguard

>So it seems that its signing method is not compatible with the T440.

correct

>Is there another signing tool or method that might work here?

Not that I know of
