### ISSUE TITLE
Thinkpad X1 tablet 3gen

### ISSUE THREAD

**Issue by Vorshim92** [digmorepaka/thinkpad-firmware-patches#31]
hi! anyone knows which patch can I use for ThinkPad X1 tablet 3gen?

**Comment by Some0nee** [comment]
I believe the xx70-xx80 patches work, because it does put the TPM into MFG Mode. But without a TXT bios gui instead of the lame "ThinkPad Tablet Setup", You actually cannot see the advanced menu because "Date/Time" tab doesn't exist on this BIOS menu. If we can find a way to revert from this BIOS GUI into the TXT version, then maybe it would work.

**Comment by Some0nee** [comment]
I got it working for the X1 Tablet Gen 3. We just had to move it to a different tab.

**Comment by Some0nee** [comment]
Created a pull request and added support for this device.

**Comment by Some0nee** [comment]
@digmorepaka Please close issue.
