### ISSUE TITLE
ThinkPad x280

### ISSUE THREAD

**Issue by WhiteFossa** [digmorepaka/thinkpad-firmware-patches#33]
Model: ThinkPad x280
Patchset: xx70_xx80_patches_v7.txt with all patches (nothig commented out)
TPM: 4C 4E 56 42 42 53 45 43 FB -> 4C 4E 56 42 42 53 45 43 FF

Notes: Do not use fix_vendor_hashes.py, it damages patched bios file and machine becomes unbootable. Just patch and change sequence (above).

TPM stick in "MFG mode".

**Comment by koshkamau** [comment]
Thank you for your comment.
Same situation with x240.
I used https://github.com/thrimbor/thinkpad-uefi-sign and it made my laptop unbootable. It even looked like some short circuit or power failure because laptop switched off in a fraction of a second.

everything else works fine. I got whitelist removed.
